version: '3'
services:
  movies:
    image: jameema25/moviesservice:latest
    ports:
      - "80:80"
    deploy:
      replicas: 3
  train:
    image: jameema25/trainservice:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  dth:
    image: jameema25/dthservice:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  recharge:
    image: jameema25/rechargeservice:latest
    ports:
      -"83:80"
    deploy:
      replicas: 3



